general:
steps:
  cloudFoundryDeploy:
    deployTool: 'cf_native'
    deployType: 'standard'
    verbbose: 'true'
    cloudFoundry:
      org: 'P1940751883trial_trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
