general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    mtaBuildTool: 'classic'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: '47dac577trial'
      space: 'dev'
      credentialsId: 'CF-devsecops20'
