general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'P1940751883trial_trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
