general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    platform: 'cf'
    mtaBuildTool: 'classic'
    verbbose: 'true'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    verbbose: 'true'
    cloudFoundry:
      org: 'P1940751883trial_trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
