general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder'
    mtaJarLocation: '/opt/mta_archive_builder-1.1.20.jar'
    platform: 'cf'
    mtaBuildTool: 'classic'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'P1940751883trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
