general:
steps:
  tmsUpload:
    credentialsId: ServiceKeyTMS
    nodeName: Dev
    mtaPath: '/var/lib/jenkins/workspace/SCPDeploy_CF_Chat_Local_master'
    customDescription: Transport from Piper
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    verbbose: 'true'
    cloudFoundry:
      org: 'P1940751883trial_trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
