general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder'
    mtaJarLocation: '/opt/sap/mta/lib/mta.jar'
    mtaBuildTool: 'classic'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'P1940751883trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
